.TH jscli 1
.SH NAME
jscli \- Create JS/TS Projects
.SH SYNOPSIS
.B js
create
project
[FRAMEWORK]
[PROJECT NAME]
.SH DESCRIPTION
.B jscli
A CLI tool that helps in creating JavaScript/TypeScript projects using frameworks like React, Svelte, etc.
.SH OPTIONS
.TP
.BR [FRAMEWORK]
Framework to use for the project.
.TP
.BR [PROJECT NAME]
Name for the project.
